/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val f1 = Fraccion(3, 4)
    f1.mostrar()  // Imprime: 3/4
    
    val f2 = Fraccion(1, 2)
    println(f2)   // Imprime: 1/2
}